markdown: kramdown
pygments: true
auto: true

#url: http://localhost:4000
url: http://www.peterbrandt.com.au
#url: http://veromary.github.io/peterbrandt.com.au

excerpt_separator: <!--more-->

paginate: 5

paginate_path: "page:num"
