markdown: kramdown
#auto: true

#url: http://localhost:4000
url: http://blog.peterbrandt.com.au
#url: http://veromary.github.io/peterbrandt.com.au

excerpt_separator: <!--more-->

paginate: 5

paginate_path: "blog/page:num"

